# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nicolas medeiros
email: nicolasmedeiros@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineer from Montevideo, Uruguay.  I'm passionate about software, reading and TV. I specialize in web development and agile methodologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nicolasmedeiros.com" # the base hostname & protocol for your site
twitter_username: kurtkbrain
github_username:  nicolasiugo

# Build settings
markdown: kramdown


#github
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
	noscript: false